using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Dash
{
    class Level
    {
        private int type;
        private GameObject[,] levelMap;
        private GameObject[,] backgroundMap;
        private int time;
        private int gravity;

        private GameObject[,] bla = new GameObject[14, 26]
                                    {
                                        {new GridBlock(new PointF(0,0),""),new GridBlock(new PointF(0,0),""),new GridBlock(new PointF(0,0),""),new GridBlock(new PointF(0,0),""),new GridBlock(new PointF(0,0),""),new GridBlock(new PointF(0,0),""),new GridBlock(new PointF(0,0),""),new GridBlock(new PointF(0,0),""),new GridBlock(new PointF(0,0),""),new GridBlock(new PointF(0,0),""),new GridBlock(new PointF(0,0),""),new GridBlock(new PointF(0,0),""),new GridBlock(new PointF(0,0),""),new GridBlock(new PointF(0,0),""),new GridBlock(new PointF(0,0),""),new GridBlock(new PointF(0,0),""),new GridBlock(new PointF(0,0),""),new GridBlock(new PointF(0,0),""),new GridBlock(new PointF(0,0),""),new GridBlock(new PointF(0,0),""),new GridBlock(new PointF(0,0),""),new GridBlock(new PointF(0,0),""),new GridBlock(new PointF(0,0),""),new GridBlock(new PointF(0,0),""),new GridBlock(new PointF(0,0),""),new GridBlock(new PointF(0,0),"")},
                                        {new GridBlock(new PointF(0,0),""),new GridBlock(new PointF(0,0),""),new GridBlock(new PointF(0,0),""),new GridBlock(new PointF(0,0),""),new GridBlock(new PointF(0,0),""),new GridBlock(new PointF(0,0),""),new GridBlock(new PointF(0,0),""),new GridBlock(new PointF(0,0),""),new GridBlock(new PointF(0,0),""),new GridBlock(new PointF(0,0),""),new GridBlock(new PointF(0,0),""),new GridBlock(new PointF(0,0),""),new GridBlock(new PointF(0,0),""),new GridBlock(new PointF(0,0),""),new GridBlock(new PointF(0,0),""),new GridBlock(new PointF(0,0),""),new GridBlock(new PointF(0,0),""),new GridBlock(new PointF(0,0),""),new GridBlock(new PointF(0,0),""),new GridBlock(new PointF(0,0),""),new GridBlock(new PointF(0,0),""),new GridBlock(new PointF(0,0),""),new GridBlock(new PointF(0,0),""),new GridBlock(new PointF(0,0),""),new GridBlock(new PointF(0,0),""),new GridBlock(new PointF(0,0),"")},
                                        {new GridBlock(new PointF(0,0),""),new GridBlock(new PointF(0,0),""),new GridBlock(new PointF(0,0),""),new GridBlock(new PointF(0,0),""),new GridBlock(new PointF(0,0),""),new GridBlock(new PointF(0,0),""),new GridBlock(new PointF(0,0),""),new GridBlock(new PointF(0,0),""),new GridBlock(new PointF(0,0),""),new GridBlock(new PointF(0,0),""),new GridBlock(new PointF(0,0),""),new GridBlock(new PointF(0,0),""),new GridBlock(new PointF(0,0),""),new GridBlock(new PointF(0,0),""),new GridBlock(new PointF(0,0),""),new GridBlock(new PointF(0,0),""),new GridBlock(new PointF(0,0),""),new GridBlock(new PointF(0,0),""),new GridBlock(new PointF(0,0),""),new GridBlock(new PointF(0,0),""),new GridBlock(new PointF(0,0),""),new GridBlock(new PointF(0,0),""),new GridBlock(new PointF(0,0),""),new GridBlock(new PointF(0,0),""),new GridBlock(new PointF(0,0),""),new GridBlock(new PointF(0,0),"")},
                                        {new GridBlock(new PointF(0,0),""),new GridBlock(new PointF(0,0),""),new GridBlock(new PointF(0,0),""),new GridBlock(new PointF(0,0),""),new GridBlock(new PointF(0,0),""),new GridBlock(new PointF(0,0),""),new GridBlock(new PointF(0,0),""),new GridBlock(new PointF(0,0),""),new GridBlock(new PointF(0,0),""),new GridBlock(new PointF(0,0),""),new GridBlock(new PointF(0,0),""),new GridBlock(new PointF(0,0),""),new GridBlock(new PointF(0,0),""),new GridBlock(new PointF(0,0),""),new GridBlock(new PointF(0,0),""),new GridBlock(new PointF(0,0),""),new GridBlock(new PointF(0,0),""),new GridBlock(new PointF(0,0),""),new GridBlock(new PointF(0,0),""),new GridBlock(new PointF(0,0),""),new GridBlock(new PointF(0,0),""),new GridBlock(new PointF(0,0),""),new GridBlock(new PointF(0,0),""),new GridBlock(new PointF(0,0),""),new GridBlock(new PointF(0,0),""),new GridBlock(new PointF(0,0),"")},
                                        {new GridBlock(new PointF(0,0),""),new GridBlock(new PointF(0,0),""),new GridBlock(new PointF(0,0),""),new GridBlock(new PointF(0,0),""),new GridBlock(new PointF(0,0),""),new GridBlock(new PointF(0,0),""),new GridBlock(new PointF(0,0),""),new GridBlock(new PointF(0,0),""),new GridBlock(new PointF(0,0),""),new GridBlock(new PointF(0,0),""),new GridBlock(new PointF(0,0),""),new GridBlock(new PointF(0,0),""),new GridBlock(new PointF(0,0),""),new GridBlock(new PointF(0,0),""),new GridBlock(new PointF(0,0),""),new GridBlock(new PointF(0,0),""),new GridBlock(new PointF(0,0),""),new GridBlock(new PointF(0,0),""),new GridBlock(new PointF(0,0),""),new GridBlock(new PointF(0,0),""),new GridBlock(new PointF(0,0),""),new GridBlock(new PointF(0,0),""),new GridBlock(new PointF(0,0),""),new GridBlock(new PointF(0,0),""),new GridBlock(new PointF(0,0),""),new GridBlock(new PointF(0,0),"")},
                                        {new GridBlock(new PointF(0,0),""),new GridBlock(new PointF(0,0),""),new GridBlock(new PointF(0,0),""),new GridBlock(new PointF(0,0),""),new GridBlock(new PointF(0,0),""),new GridBlock(new PointF(0,0),""),new GridBlock(new PointF(0,0),""),new GridBlock(new PointF(0,0),""),new GridBlock(new PointF(0,0),""),new GridBlock(new PointF(0,0),""),new GridBlock(new PointF(0,0),""),new GridBlock(new PointF(0,0),""),new GridBlock(new PointF(0,0),""),new GridBlock(new PointF(0,0),""),new GridBlock(new PointF(0,0),""),new GridBlock(new PointF(0,0),""),new GridBlock(new PointF(0,0),""),new GridBlock(new PointF(0,0),""),new GridBlock(new PointF(0,0),""),new GridBlock(new PointF(0,0),""),new GridBlock(new PointF(0,0),""),new GridBlock(new PointF(0,0),""),new GridBlock(new PointF(0,0),""),new GridBlock(new PointF(0,0),""),new GridBlock(new PointF(0,0),""),new GridBlock(new PointF(0,0),"")},
                                        {new GridBlock(new PointF(0,0),""),new GridBlock(new PointF(0,0),""),new GridBlock(new PointF(0,0),""),new GridBlock(new PointF(0,0),""),new GridBlock(new PointF(0,0),""),new GridBlock(new PointF(0,0),""),new GridBlock(new PointF(0,0),""),new GridBlock(new PointF(0,0),""),new GridBlock(new PointF(0,0),""),new GridBlock(new PointF(0,0),""),new GridBlock(new PointF(0,0),""),new GridBlock(new PointF(0,0),""),new GridBlock(new PointF(0,0),""),new GridBlock(new PointF(0,0),""),new GridBlock(new PointF(0,0),""),new GridBlock(new PointF(0,0),""),new GridBlock(new PointF(0,0),""),new GridBlock(new PointF(0,0),""),new GridBlock(new PointF(0,0),""),new GridBlock(new PointF(0,0),""),new GridBlock(new PointF(0,0),""),new GridBlock(new PointF(0,0),""),new GridBlock(new PointF(0,0),""),new GridBlock(new PointF(0,0),""),new GridBlock(new PointF(0,0),""),new GridBlock(new PointF(0,0),"")},
                                        {new GridBlock(new PointF(0,0),""),new GridBlock(new PointF(0,0),""),new GridBlock(new PointF(0,0),""),new GridBlock(new PointF(0,0),""),new GridBlock(new PointF(0,0),""),new GridBlock(new PointF(0,0),""),new GridBlock(new PointF(0,0),""),new GridBlock(new PointF(0,0),""),new GridBlock(new PointF(0,0),""),new GridBlock(new PointF(0,0),""),new GridBlock(new PointF(0,0),""),new GridBlock(new PointF(0,0),""),new GridBlock(new PointF(0,0),""),new GridBlock(new PointF(0,0),""),new GridBlock(new PointF(0,0),""),new GridBlock(new PointF(0,0),""),new GridBlock(new PointF(0,0),""),new GridBlock(new PointF(0,0),""),new GridBlock(new PointF(0,0),""),new GridBlock(new PointF(0,0),""),new GridBlock(new PointF(0,0),""),new GridBlock(new PointF(0,0),""),new GridBlock(new PointF(0,0),""),new GridBlock(new PointF(0,0),""),new GridBlock(new PointF(0,0),""),new GridBlock(new PointF(0,0),"")},
                                        {new GridBlock(new PointF(0,0),""),new GridBlock(new PointF(0,0),""),new GridBlock(new PointF(0,0),""),new GridBlock(new PointF(0,0),""),new GridBlock(new PointF(0,0),""),new GridBlock(new PointF(0,0),""),new GridBlock(new PointF(0,0),""),new GridBlock(new PointF(0,0),""),new GridBlock(new PointF(0,0),""),new GridBlock(new PointF(0,0),""),new GridBlock(new PointF(0,0),""),new GridBlock(new PointF(0,0),""),new GridBlock(new PointF(0,0),""),new GridBlock(new PointF(0,0),""),new GridBlock(new PointF(0,0),""),new GridBlock(new PointF(0,0),""),new GridBlock(new PointF(0,0),""),new GridBlock(new PointF(0,0),""),new GridBlock(new PointF(0,0),""),new GridBlock(new PointF(0,0),""),new GridBlock(new PointF(0,0),""),new GridBlock(new PointF(0,0),""),new GridBlock(new PointF(0,0),""),new GridBlock(new PointF(0,0),""),new GridBlock(new PointF(0,0),""),new GridBlock(new PointF(0,0),"")},
                                        {new GridBlock(new PointF(0,0),""),new GridBlock(new PointF(0,0),""),new GridBlock(new PointF(0,0),""),new GridBlock(new PointF(0,0),""),new GridBlock(new PointF(0,0),""),new GridBlock(new PointF(0,0),""),new GridBlock(new PointF(0,0),""),new GridBlock(new PointF(0,0),""),new GridBlock(new PointF(0,0),""),new GridBlock(new PointF(0,0),""),new GridBlock(new PointF(0,0),""),new GridBlock(new PointF(0,0),""),new GridBlock(new PointF(0,0),""),new GridBlock(new PointF(0,0),""),new GridBlock(new PointF(0,0),""),new GridBlock(new PointF(0,0),""),new GridBlock(new PointF(0,0),""),new GridBlock(new PointF(0,0),""),new GridBlock(new PointF(0,0),""),new GridBlock(new PointF(0,0),""),new GridBlock(new PointF(0,0),""),new GridBlock(new PointF(0,0),""),new GridBlock(new PointF(0,0),""),new GridBlock(new PointF(0,0),""),new GridBlock(new PointF(0,0),""),new GridBlock(new PointF(0,0),"")},
                                        {new GridBlock(new PointF(0,0),""),new GridBlock(new PointF(0,0),""),new GridBlock(new PointF(0,0),""),new GridBlock(new PointF(0,0),""),new GridBlock(new PointF(0,0),""),new GridBlock(new PointF(0,0),""),new GridBlock(new PointF(0,0),""),new GridBlock(new PointF(0,0),""),new GridBlock(new PointF(0,0),""),new GridBlock(new PointF(0,0),""),new GridBlock(new PointF(0,0),""),new GridBlock(new PointF(0,0),""),new GridBlock(new PointF(0,0),""),new GridBlock(new PointF(0,0),""),new GridBlock(new PointF(0,0),""),new GridBlock(new PointF(0,0),""),new GridBlock(new PointF(0,0),""),new GridBlock(new PointF(0,0),""),new GridBlock(new PointF(0,0),""),new GridBlock(new PointF(0,0),""),new GridBlock(new PointF(0,0),""),new GridBlock(new PointF(0,0),""),new GridBlock(new PointF(0,0),""),new GridBlock(new PointF(0,0),""),new GridBlock(new PointF(0,0),""),new GridBlock(new PointF(0,0),"")},
                                        {new GridBlock(new PointF(0,0),""),new GridBlock(new PointF(0,0),""),new GridBlock(new PointF(0,0),""),new GridBlock(new PointF(0,0),""),new GridBlock(new PointF(0,0),""),new GridBlock(new PointF(0,0),""),new GridBlock(new PointF(0,0),""),new GridBlock(new PointF(0,0),""),new GridBlock(new PointF(0,0),""),new GridBlock(new PointF(0,0),""),new GridBlock(new PointF(0,0),""),new GridBlock(new PointF(0,0),""),new GridBlock(new PointF(0,0),""),new GridBlock(new PointF(0,0),""),new GridBlock(new PointF(0,0),""),new GridBlock(new PointF(0,0),""),new GridBlock(new PointF(0,0),""),new GridBlock(new PointF(0,0),""),new GridBlock(new PointF(0,0),""),new GridBlock(new PointF(0,0),""),new GridBlock(new PointF(0,0),""),new GridBlock(new PointF(0,0),""),new GridBlock(new PointF(0,0),""),new GridBlock(new PointF(0,0),""),new GridBlock(new PointF(0,0),""),new GridBlock(new PointF(0,0),"")},
                                        {new GridBlock(new PointF(0,0),""),new GridBlock(new PointF(0,0),""),new GridBlock(new PointF(0,0),""),new GridBlock(new PointF(0,0),""),new GridBlock(new PointF(0,0),""),new GridBlock(new PointF(0,0),""),new GridBlock(new PointF(0,0),""),new GridBlock(new PointF(0,0),""),new GridBlock(new PointF(0,0),""),new GridBlock(new PointF(0,0),""),new GridBlock(new PointF(0,0),""),new GridBlock(new PointF(0,0),""),new GridBlock(new PointF(0,0),""),new GridBlock(new PointF(0,0),""),new GridBlock(new PointF(0,0),""),new GridBlock(new PointF(0,0),""),new GridBlock(new PointF(0,0),""),new GridBlock(new PointF(0,0),""),new GridBlock(new PointF(0,0),""),new GridBlock(new PointF(0,0),""),new GridBlock(new PointF(0,0),""),new GridBlock(new PointF(0,0),""),new GridBlock(new PointF(0,0),""),new GridBlock(new PointF(0,0),""),new GridBlock(new PointF(0,0),""),new GridBlock(new PointF(0,0),"")},
                                        {new GridBlock(new PointF(0,0),""),new GridBlock(new PointF(0,0),""),new GridBlock(new PointF(0,0),""),new GridBlock(new PointF(0,0),""),new GridBlock(new PointF(0,0),""),new GridBlock(new PointF(0,0),""),new GridBlock(new PointF(0,0),""),new GridBlock(new PointF(0,0),""),new GridBlock(new PointF(0,0),""),new GridBlock(new PointF(0,0),""),new GridBlock(new PointF(0,0),""),new GridBlock(new PointF(0,0),""),new GridBlock(new PointF(0,0),""),new GridBlock(new PointF(0,0),""),new GridBlock(new PointF(0,0),""),new GridBlock(new PointF(0,0),""),new GridBlock(new PointF(0,0),""),new GridBlock(new PointF(0,0),""),new GridBlock(new PointF(0,0),""),new GridBlock(new PointF(0,0),""),new GridBlock(new PointF(0,0),""),new GridBlock(new PointF(0,0),""),new GridBlock(new PointF(0,0),""),new GridBlock(new PointF(0,0),""),new GridBlock(new PointF(0,0),""),new GridBlock(new PointF(0,0),"")}
                                    };
        

        
        public int Type
        {
            get { return type; }
        }

        public GameObject[,] LevelMap
        {
            get { return levelMap; }
        }

        public GameObject[,] BackgroundMap
        {
            get { return backgroundMap; }
        }

        public int Time
        {
            get { return time; }
        }

        public int Gravity
        {
            get { return gravity; }
        }
    }
}
